config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :announcements
      resources :notifications
      resources :services

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :cards do
    member do
      patch :move
    end
  end

  resources :lists do
    member do
      patch :move
    end
  end

  root to: 'lists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/list.rb
class List < ApplicationRecord
  acts_as_list

  has_many :cards, ->{ order(position: :asc) }, dependent: :destroy

  scope :sorted, ->{ order(position: :asc) }

  validates :name, presence: true
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy, :move]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.sorted
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        ActionCable.server.broadcast "board", { commit: 'addList', payload: render_to_string(:show, format: :json) }
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def move
    @list.insert_at(list_params[:position].to_i)
    render action: :show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :position)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if list.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', list, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if list.persisted? %>
      <%= link_to "Cancel", list, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", lists_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<%= render 'form', list: @list %>

app/views/lists/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Lists</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_list_path, class: 'btn btn-primary' do %>
    Add New List
  <% end %>
  </div>
</div>

<%= tag.div id: :boards, data: { lists: @lists.to_json(include: :cards) } %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form', list: @list %>

app/views/lists/show.html.erb
<div class="page-header">
  <%= link_to lists_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    All Lists
  <% end %>
  <%= link_to edit_list_path(@list), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show list</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @list.name %></dd>

  <dt>Position:</dt>
  <dd><%= @list.position %></dd>

</dl>