config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :announcements
      resources :notifications
      resources :services

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :cards do
    member do
      patch :move
    end
  end

  resources :lists do
    member do
      patch :move
    end
  end

  root to: 'lists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
  acts_as_list scope: :list

  belongs_to :list

  validates :name, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy, :move]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        ActionCable.server.broadcast "board", { commit: 'addCard', payload: render_to_string(:show, format: :json) }
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        ActionCable.server.broadcast "board", { commit: 'editCard', payload: render_to_string(:show, format: :json) }
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def move
    @card.update(card_params)
    render action: :show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:list_id, :name, :position)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :list_id %>
    <%= form.text_field :list_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :position %>
    <%= form.number_field :position, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if card.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', card, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if card.persisted? %>
      <%= link_to "Cancel", card, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", cards_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Edit Card</h1>

<%= render 'form', card: @card %>

app/views/cards/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Cards</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_card_path, class: 'btn btn-primary' do %>
    Add New Card
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    
        <th>Name</th>
    

            <th>List</th>
            <th>Position</th>
            
      </tr>
    </thead>

    <tbody>
      <% @cards.each do |card| %>
        <%= content_tag :tr, id: dom_id(card), class: dom_class(card) do %>
          
            <td><%= link_to card.name, card %></td>
          

                      <td><%= card.list %></td>
                      <td><%= card.position %></td>
          
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form', card: @card %>

app/views/cards/show.html.erb
<div class="page-header">
  <%= link_to cards_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    All Cards
  <% end %>
  <%= link_to edit_card_path(@card), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show card</h1>
</div>

<dl class="dl-horizontal">
  <dt>List:</dt>
  <dd><%= @card.list %></dd>

  <dt>Name:</dt>
  <dd><%= @card.name %></dd>

  <dt>Position:</dt>
  <dd><%= @card.position %></dd>

</dl>